---
- name: check if cargo exists
  shell: command -v cargo
  register: cargo_check
  ignore_errors: yes

- name: Download rust setup script
  when: cargo_check is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"

- name: run Rust install script
  shell: /tmp/sh.rustup.rs -y
  when: cargo_check is failed
