- name: "Install pipx tools"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.source }}"
    state: latest
  loop:
    - {name: 'netexec', source: 'git+https://github.com/Pennyw0rth/NetExec'}